version: '3'
services:
  mysql:
    container_name: mysql-ocr
    image: mysql:oracle
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=ocr
      - MYSQL_ROOT_PASSWORD=root

  rabbitmq:
    container_name: rabbit-mq
    image: rabbitmq
    ports:
      - "5672:5672"
    restart: always

